package com.astreal.client;

import com.astreal.client.modules.ModuleManager;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Astreal Client — generated by Astreal Studios
 * Minecraft 1.21.11
 * Features: Fullbright, Zoom, FPS Display, Toggle Sprint, Keystrokes HUD, CPS Counter, Armor Status, Scoreboard Tweaks, Direction HUD, Potion Effects HUD, Item Cooldown, Crosshair Customizer, Hitbox Overlay, Chunk Borders, Freelook, Motion Blur, No Hurtcam, Cape Support, Wings, Hat Cosmetics, Particle Trail, Animated Cape, Skin Effects, Waypoints, Minimap, Auto Sprint, Hit Color, Block Overlay
 */
@Environment(EnvType.CLIENT)
public class AstrealClient implements ClientModInitializer {
    public static final String        MOD_ID        = "astreal-client";
    public static final Logger        LOGGER        = LoggerFactory.getLogger(MOD_ID);
    public static       ModuleManager moduleManager;

    @Override
    public void onInitializeClient() {
        LOGGER.info("Astreal Client initializing for Minecraft 1.21.11...");
        moduleManager = new ModuleManager();
        moduleManager.init();
        LOGGER.info("Astreal Client initialized {} modules.", moduleManager.getModules().size());
    }
}
